---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - WEBUI_PORT=8989
    volumes:
      - /mnt/nfs/docker/qbitorrent/config:/config
      - /mnt/nfs/data/downloads:/downloads
    ports:
      - 6881-6889:6881-6889
      - 6881-6889:6881-6889/udp
      - 8989:8989
    restart: unless-stopped
