---
version: "2"
services:
  nginx:
    image: nginx
    container_name: k3s-nginx-lb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 6443:6443
    restart: unless-stopped
