---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack:22.03.1
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.comprofix.xyz/
      - DB_HOST=192.168.50.2
      - DB_USER=bookstack
      - DB_PASS=bookstackpass
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/nfs/docker/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
