version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8181:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /mnt/nfs/docker/speedtest/config:/config
            - /mnt/nfs/docker/speedtest/web:/etc/ssl/web
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        restart: unless-stopped