---
version: "2.1"
services:
  couchpotato:
    image: v2tec/watchtower
    container_name: watchtower
    environment:
        - TZ=Australia/Brisbane
        - WATCHTOWER_SCHEDULE=0 0 4 * * *
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_NOTIFICATIONS=slack
        - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: DISCORD_HOOK
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
