---
version: "2.1"
services:
  couchpotato:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
        TZ: "Australia/Brisbane"
        WATCHTOWER_SCHEDULE: "0 0 4 * * *"
        WATCHTOWER_CLEANUP: "true"
        WATCHTOWER_NOTIFICATIONS: gotify
        WATCHTOWER_NOTIFICATION_GOTIFY_URL: "https://gotify.comprofix.com/"
        WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: ${GOTIFY_TOKEN}
        WATCHTOWER_WARN_ON_HEAD_FAILURE: never
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped