---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - AUTO_UPDATE=true #optional
    volumes:
      - /mnt/nfs/docker/jackett/config:/config
      - /mnt/nfs/data/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
