version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    environment:
      DOZZLE_LEVEL: trace
      DOZZLE_REMOTE_HOST: tcp://docker.comprofix.xyz:2375,tcp://ha-server.comprofix.xyz:2375,tcp://omada-server.comprofix.xyz:2375
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    
    

   