---
version: "2.1"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/nfs/docker/freshrss/config:/config
    ports:
      - 8981:80
    restart: unless-stopped